/*
 * generated by Xtext
 */
package de.itemis.xtext.antlr.splitting;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleExpressionsRuntimeModule extends de.itemis.xtext.antlr.splitting.AbstractSimpleExpressionsRuntimeModule {

}
